[project]
name = "learn-reasoning-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.2",
    "requests>=2.32.5",
    "tokenizer>=3.6.2",
    "tokenizers>=0.22.2",
    "torch>=2.10.0",
]
